[toolchain]

[features]
resolution = true
skip-lint = false


[programs.devnet]
deadmint = "Aj2fUK4fdw6Y6BCgtuUPsBL761AAgFjNjzt5Zd3Sp2Qb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/deadmint"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deadmint-anchor.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://devnet.helius-rpc.com/?api-key=90a86d9d-6820-4f75-9f5b-c8099b59eef9"
ledger = ".anchor/test-ledger"
rpc_port = 8899
