[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
deadmint = "Aup9nTYaxPfvXiu4jLzj4oQQXwkJe5CiyBixRb57wfZM"

[programs.devnet]
deadmint = "Aup9nTYaxPfvXiu4jLzj4oQQXwkJe5CiyBixRb57wfZM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/deadmint"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deadmint-anchor.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
